language: objective-c
osx_image: xcode10.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=FillTheTank.xcodeproj
  - WORKSPACE=FillTheTank.xcworkspace
  - IOS_SDK=iphonesimulator12.2
  - IOS_FRAMEWORK_SCHEME="FillTheTank"
  - EXAMPLE_SCHEME="FillTheTankDemo"
  matrix:
    - DESTINATION="OS=12.2,name=iPhone Xs"     SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="NO" POD_LINT="YES"

cache: cocoapods
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --repo-update

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -list
  - xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME"  -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES   test | xcpretty;

notifications:
  slack:
    secure: RKaNg07XZBYwXwpBCA2Bz5Ru1U3MppWRXxz2WmU7JWfNr4F7Q6PeiES+MlIJdbNHG7VUBs5hmouqTHelLdHdy16hOBIYsxZymqGG4HeNgfuKGaNnuEwd+HC4cvh7XzLVAU6Gl8HDhZ7Mxqzeahq7KJWaYl5EMspfNJJYXm0tToXRpkvpcsoJcdDbgpmr8xHNzU2eqD+ZekNw9s2H8Q2v8ijJuU01QPYLp7d08gAgR7x8P/3gn+uyP+stL6fNQaRF/gbkrhebh26Xm/D1AtjhfDTFxThQ+MRd010zZNu4mqizvR8bH2+yGGqskdLNE7MpaMOs09vptS9XdiN+6SzzS8yL7+5vnP6KTW1e6UkRL7dgyMkUOmkg0mJiNyj9xtS3EXrch68xo1r2WQowxDg47BbWMBLuQFTOo/BhbrdHkJrmL4A3nbhsfPSHpuEzyrvLS2w90Asfw2l+ui5QncuQNJJToXMoZVAFjhxeRpbXUKh6UlPQhWFFuTwfi+Q/b4vy4QhE7KZyZcq/OBIMpm+e0Ou5/xpaR6l6H97+C+tlq0EYGZxhx7S2/jWxZGJHCXgT1oDpQJMOvnKxxIpsS7KsLxLfWOSzsBBroOjsMrYLqW1XzjkYxKvuGIuZndxLGSdg4BLBWpQTMwUY5xrhGze7W/CA/wfyGZryc2/jKBp2U5E=
